import Form from '@/components/Form';
import Table from '@/components/Table';
import Head from 'next/head';
import { useState } from 'react';
import { BiUserPlus } from 'react-icons/bi';

export default function Home() {
  const [visible, setVisible] = useState(false);

  const handler = () => {
    {
      /*toggling add employee button*/
    }
    // setVisible(visible ? false : true);
    setVisible(!visible);
  };

  return (
    <>
      <section>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="py-5">
          <h1 className="text-xl md:text-5xl text-center font-bold py-10 capitalize">
            employee management system
          </h1>

          {/*add employee handler*/}
          <div className="container mx-auto flex justify-between py-5 border-b">
            <div className="left flex gap-3">
              <button onClick={handler} type="" className="empl_button">
                add employee{' '}
                <span className="px-1">
                  <BiUserPlus size={23} />
                </span>
              </button>
            </div>
          </div>

          {/*collapsable form*/}
          {visible ? <Form /> : ''}

          {/*Table*/}
          <div className="container mx-auto">
            <Table />
          </div>
        </main>
      </section>
    </>
  );
}
